version: '3'

services:

  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: news
    ports:
      - "3306:3306"
    volumes:
        - data:/var/lib/mysql

volumes:
  data:
